<?php

namespace express_4px\oms\fu_wms_outbound_getbilling\v100;

class GetOutboundBillingErrorCode{
	const ERR_OUTBOUND_CONSIGNMENT_CONSIGNMENTNO_AND_REFNO_EMPTY= 'ERR_OUTBOUND_CONSIGNMENT_CONSIGNMENTNO_AND_REFNO_EMPTY';
	const ERR_OUTBOUND_CONSIGNMENT_REFNO_NOT_EXIST= 'ERR_OUTBOUND_CONSIGNMENT_REFNO_NOT_EXIST';
	const ERR_OUTBOUND_CONSIGNMENT_QUERY_BILLING_FAIL= 'ERR_OUTBOUND_CONSIGNMENT_QUERY_BILLING_FAIL';
	
	static $codeMessageMap = array(
		self::ERR_OUTBOUND_CONSIGNMENT_CONSIGNMENTNO_AND_REFNO_EMPTY => '出库委托单号和参考号不能全为空',
		self::ERR_OUTBOUND_CONSIGNMENT_REFNO_NOT_EXIST               => '参考号不存在',
		self::ERR_OUTBOUND_CONSIGNMENT_QUERY_BILLING_FAIL            => '出库委托单查询计费失败',
	);
	
}