<?php

namespace express_4px\oms\fu_wms_inbound_getlist\v100;

class GetInboundListErrorCode{
	const ERR_INBOUND_CONSIGNMENT_PAGE_SIZE_TOO_LARGE= 'ERR_INBOUND_CONSIGNMENT_PAGE_SIZE_TOO_LARGE';
	const ERR_INBOUND_CONSIGNMENT_CREATE_TIME_START_EMPTY= 'ERR_INBOUND_CONSIGNMENT_CREATE_TIME_START_EMPTY';
	const ERR_INBOUND_CONSIGNMENT_CREATE_TIME_END_EMPTY= 'ERR_INBOUND_CONSIGNMENT_CREATE_TIME_END_EMPTY';
	const ERR_INBOUND_CONSIGNMENT_BETWEEN_TOO_LARGE= 'ERR_INBOUND_CONSIGNMENT_BETWEEN_TOO_LARGE';
	
	static $codeMessageMap = array(
		self::ERR_INBOUND_CONSIGNMENT_PAGE_SIZE_TOO_LARGE     => '页面大小大于100',
		self::ERR_INBOUND_CONSIGNMENT_CREATE_TIME_START_EMPTY => '起始时间不能为空',
		self::ERR_INBOUND_CONSIGNMENT_CREATE_TIME_END_EMPTY   => '结束时间不能为空',
		self::ERR_INBOUND_CONSIGNMENT_BETWEEN_TOO_LARGE       => '查询时间跨度最长为90天',
	);
	
}