<?php

namespace express_4px\oms\com_basis_declare_create\v100;

class CreateDeclareErrorCode{
	const ERR_DECLARE_GOODS_CODE_EMPTY= 'ERR_DECLARE_GOODS_CODE_EMPTY';
	const ERR_DECLARE_GOODS_CODE_LENGTH_GT_20= 'ERR_DECLARE_GOODS_CODE_LENGTH_GT_20';
	const ERR_DECLARE_GOODS_GROUP_ID_EMPTY= 'ERR_DECLARE_GOODS_GROUP_ID_EMPTY';
	const ERR_DECLARE_GOODS_GROUP_ID_LENGTH_GT_10= 'ERR_DECLARE_GOODS_GROUP_ID_LENGTH_GT_10';
	const ERR_DECLARE_GOODS_PURPOSE_EMPTY= 'ERR_DECLARE_GOODS_PURPOSE_EMPTY';
	const ERR_DECLARE_GOODS_USES_LENGTH_GT_500= 'ERR_DECLARE_GOODS_USES_LENGTH_GT_500';
	const ERR_DECLARE_GOODS_SPECIFICATION_EMPTY= 'ERR_DECLARE_GOODS_SPECIFICATION_EMPTY';
	const ERR_DECLARE_GOODS_SPEC_LENGTH_GT_500= 'ERR_DECLARE_GOODS_SPEC_LENGTH_GT_500';
	const ERR_DECLARE_GOODS_MODEL_LENGTH_GT_100= 'ERR_DECLARE_GOODS_MODEL_LENGTH_GT_100';
	const ERR_DECLARE_GOODS_MATERIAL_EMPTY= 'ERR_DECLARE_GOODS_MATERIAL_EMPTY';
	const ERR_DECLARE_GOODS_MATERIAL_LENGTH_GT_500= 'ERR_DECLARE_GOODS_MATERIAL_LENGTH_GT_500';
	const ERR_DECLARE_GOODS_ORIGIN_COUNTRY_EMPTY= 'ERR_DECLARE_GOODS_ORIGIN_COUNTRY_EMPTY';
	const ERR_DECLARE_GOODS_CODE_LENGTH_GT_21= 'ERR_DECLARE_GOODS_CODE_LENGTH_GT_21';
	const ERR_DECLARE_GOODS_GROUP_ID_LENGTH_GT_11= 'ERR_DECLARE_GOODS_GROUP_ID_LENGTH_GT_11';
	const ERR_DECLARE_GOODS_USES_LENGTH_GT_501= 'ERR_DECLARE_GOODS_USES_LENGTH_GT_501';
	const ERR_DECLARE_GOODS_SPEC_LENGTH_GT_501= 'ERR_DECLARE_GOODS_SPEC_LENGTH_GT_501';
	const ERR_DECLARE_GOODS_MODEL_LENGTH_GT_101= 'ERR_DECLARE_GOODS_MODEL_LENGTH_GT_101';
	const ERR_DECLARE_GOODS_MATERIAL_LENGTH_GT_501= 'ERR_DECLARE_GOODS_MATERIAL_LENGTH_GT_501';
	const ERR_DECLARE_GOODS_CODE_LENGTH_GT_22= 'ERR_DECLARE_GOODS_CODE_LENGTH_GT_22';
	const ERR_DECLARE_GOODS_GROUP_ID_LENGTH_GT_12= 'ERR_DECLARE_GOODS_GROUP_ID_LENGTH_GT_12';
	const ERR_DECLARE_GOODS_USES_LENGTH_GT_502= 'ERR_DECLARE_GOODS_USES_LENGTH_GT_502';
	const ERR_DECLARE_GOODS_SPEC_LENGTH_GT_502= 'ERR_DECLARE_GOODS_SPEC_LENGTH_GT_502';
	const ERR_DECLARE_GOODS_MODEL_LENGTH_GT_102= 'ERR_DECLARE_GOODS_MODEL_LENGTH_GT_102';
	const ERR_DECLARE_GOODS_MATERIAL_LENGTH_GT_502= 'ERR_DECLARE_GOODS_MATERIAL_LENGTH_GT_502';
	
	static $codeMessageMap = array(
		self::ERR_DECLARE_GOODS_CODE_EMPTY             => '申报产品代码不能为空',
		self::ERR_DECLARE_GOODS_CODE_LENGTH_GT_20      => '申报产品代码长度不能超过20',
		self::ERR_DECLARE_GOODS_GROUP_ID_EMPTY         => '申报品名类目ID不能为空',
		self::ERR_DECLARE_GOODS_GROUP_ID_LENGTH_GT_10  => '申报品名类目ID长度不能超过10',
		self::ERR_DECLARE_GOODS_PURPOSE_EMPTY          => '用途不能为空',
		self::ERR_DECLARE_GOODS_USES_LENGTH_GT_500     => '申报产品用途长度不能超过500',
		self::ERR_DECLARE_GOODS_SPECIFICATION_EMPTY    => '规格不能为空',
		self::ERR_DECLARE_GOODS_SPEC_LENGTH_GT_500     => '申报产品规格长度不能超过500',
		self::ERR_DECLARE_GOODS_MODEL_LENGTH_GT_100    => '申报产品型号长度不能超过100',
		self::ERR_DECLARE_GOODS_MATERIAL_EMPTY         => '材料不能为空',
		self::ERR_DECLARE_GOODS_MATERIAL_LENGTH_GT_500 => '申报产品材料长度不能超过500',
		self::ERR_DECLARE_GOODS_ORIGIN_COUNTRY_EMPTY   => '原产国不能为空',
		self::ERR_DECLARE_GOODS_CODE_LENGTH_GT_21      => '申报产品代码长度不能超过21',
		self::ERR_DECLARE_GOODS_GROUP_ID_LENGTH_GT_11  => '申报品名类目ID长度不能超过11',
		self::ERR_DECLARE_GOODS_USES_LENGTH_GT_501     => '申报产品用途长度不能超过501',
		self::ERR_DECLARE_GOODS_SPEC_LENGTH_GT_501     => '申报产品规格长度不能超过501',
		self::ERR_DECLARE_GOODS_MODEL_LENGTH_GT_101    => '申报产品型号长度不能超过101',
		self::ERR_DECLARE_GOODS_MATERIAL_LENGTH_GT_501 => '申报产品材料长度不能超过501',
		self::ERR_DECLARE_GOODS_CODE_LENGTH_GT_22      => '申报产品代码长度不能超过22',
		self::ERR_DECLARE_GOODS_GROUP_ID_LENGTH_GT_12  => '申报品名类目ID长度不能超过12',
		self::ERR_DECLARE_GOODS_USES_LENGTH_GT_502     => '申报产品用途长度不能超过502',
		self::ERR_DECLARE_GOODS_SPEC_LENGTH_GT_502     => '申报产品规格长度不能超过502',
		self::ERR_DECLARE_GOODS_MODEL_LENGTH_GT_102    => '申报产品型号长度不能超过102',
		self::ERR_DECLARE_GOODS_MATERIAL_LENGTH_GT_502 => '申报产品材料长度不能超过502',
	);
	
}