<?php

namespace express_4px\oms\data_type\common;

class CountryEnum
{
	const COUNTRY_A = 'A';
	const COUNTRY_AF = 'AF';
	const COUNTRY_AX = 'AX';
	const COUNTRY_AL = 'AL';
	const COUNTRY_DZ = 'DZ';
	const COUNTRY_AS = 'AS';
	const COUNTRY_AD = 'AD';
	const COUNTRY_AO = 'AO';
	const COUNTRY_AI = 'AI';
	const COUNTRY_AQ = 'AQ';
	const COUNTRY_AG = 'AG';
	const COUNTRY_AR = 'AR';
	const COUNTRY_AM = 'AM';
	const COUNTRY_AW = 'AW';
	const COUNTRY_AU = 'AU';
	const COUNTRY_AT = 'AT';
	const COUNTRY_AZ = 'AZ';
	const COUNTRY_BS = 'BS';
	const COUNTRY_BH = 'BH';
	const COUNTRY_BD = 'BD';
	const COUNTRY_BB = 'BB';
	const COUNTRY_BY = 'BY';
	const COUNTRY_BE = 'BE';
	const COUNTRY_BZ = 'BZ';
	const COUNTRY_BJ = 'BJ';
	const COUNTRY_BM = 'BM';
	const COUNTRY_BT = 'BT';
	const COUNTRY_BO = 'BO';
	const COUNTRY_BQ = 'BQ';
	const COUNTRY_BA = 'BA';
	const COUNTRY_BW = 'BW';
	const COUNTRY_BV = 'BV';
	const COUNTRY_BR = 'BR';
	const COUNTRY_IO = 'IO';
	const COUNTRY_BN = 'BN';
	const COUNTRY_BG = 'BG';
	const COUNTRY_BF = 'BF';
	const COUNTRY_BI = 'BI';
	const COUNTRY_CV = 'CV';
	const COUNTRY_KH = 'KH';
	const COUNTRY_CM = 'CM';
	const COUNTRY_CA = 'CA';
	const COUNTRY_KY = 'KY';
	const COUNTRY_CF = 'CF';
	const COUNTRY_TD = 'TD';
	const COUNTRY_CL = 'CL';
	const COUNTRY_CN = 'CN';
	const COUNTRY_CX = 'CX';
	const COUNTRY_CC = 'CC';
	const COUNTRY_Co = 'Co';
	const COUNTRY_KM = 'KM';
	const COUNTRY_CG = 'CG';
	const COUNTRY_CD = 'CD';
	const COUNTRY_CK = 'CK';
	const COUNTRY_CR = 'CR';
	const COUNTRY_CI = 'CI';
	const COUNTRY_HR = 'HR';
	const COUNTRY_CU = 'CU';
	const COUNTRY_CW = 'CW';
	const COUNTRY_CY = 'CY';
	const COUNTRY_CZ = 'CZ';
	const COUNTRY_DK = 'DK';
	const COUNTRY_DJ = 'DJ';
	const COUNTRY_DM = 'DM';
	const COUNTRY_DO = 'DO';
	const COUNTRY_EC = 'EC';
	const COUNTRY_EG = 'EG';
	const COUNTRY_SV = 'SV';
	const COUNTRY_GQ = 'GQ';
	const COUNTRY_ER = 'ER';
	const COUNTRY_EE = 'EE';
	const COUNTRY_ET = 'ET';
	const COUNTRY_Fk = 'Fk';
	const COUNTRY_FO = 'FO';
	const COUNTRY_FJ = 'FJ';
	const COUNTRY_FI = 'FI';
	const COUNTRY_FR = 'FR';
	const COUNTRY_GF = 'GF';
	const COUNTRY_PF = 'PF';
	const COUNTRY_TF = 'TF';
	const COUNTRY_GA = 'GA';
	const COUNTRY_GM = 'GM';
	const COUNTRY_GE = 'GE';
	const COUNTRY_DE = 'DE';
	const COUNTRY_GH = 'GH';
	const COUNTRY_GI = 'GI';
	const COUNTRY_GR = 'GR';
	const COUNTRY_GL = 'GL';
	const COUNTRY_GD = 'GD';
	const COUNTRY_GP = 'GP';
	const COUNTRY_GU = 'GU';
	const COUNTRY_GT = 'GT';
	const COUNTRY_GG = 'GG';
	const COUNTRY_GN = 'GN';
	const COUNTRY_GW = 'GW';
	const COUNTRY_GY = 'GY';
	const COUNTRY_HT = 'HT';
	const COUNTRY_HM = 'HM';
	const COUNTRY_VA = 'VA';
	const COUNTRY_HN = 'HN';
	const COUNTRY_HK = 'HK';
	const COUNTRY_HU = 'HU';
	const COUNTRY_IS = 'IS';
	const COUNTRY_IN = 'IN';
	const COUNTRY_ID = 'ID';
	const COUNTRY_IR = 'IR';
	const COUNTRY_IQ = 'IQ';
	const COUNTRY_IE = 'IE';
	const COUNTRY_IM = 'IM';
	const COUNTRY_IL = 'IL';
	const COUNTRY_IT = 'IT';
	const COUNTRY_JM = 'JM';
	const COUNTRY_JP = 'JP';
	const COUNTRY_JE = 'JE';
	const COUNTRY_JO = 'JO';
	const COUNTRY_KZ = 'KZ';
	const COUNTRY_KE = 'KE';
	const COUNTRY_KI = 'KI';
	const COUNTRY_KP = 'KP';
	const COUNTRY_KR = 'KR';
	const COUNTRY_KW = 'KW';
	const COUNTRY_KG = 'KG';
	const COUNTRY_LA = 'LA';
	const COUNTRY_LV = 'LV';
	const COUNTRY_LB = 'LB';
	const COUNTRY_LS = 'LS';
	const COUNTRY_LR = 'LR';
	const COUNTRY_LY = 'LY';
	const COUNTRY_LI = 'LI';
	const COUNTRY_LT = 'LT';
	const COUNTRY_LU = 'LU';
	const COUNTRY_MO = 'MO';
	const COUNTRY_MK = 'MK';
	const COUNTRY_MG = 'MG';
	const COUNTRY_MW = 'MW';
	const COUNTRY_MY = 'MY';
	const COUNTRY_MV = 'MV';
	const COUNTRY_ML = 'ML';
	const COUNTRY_MT = 'MT';
	const COUNTRY_MH = 'MH';
	const COUNTRY_MQ = 'MQ';
	const COUNTRY_MR = 'MR';
	const COUNTRY_MU = 'MU';
	const COUNTRY_YT = 'YT';
	const COUNTRY_MX = 'MX';
	const COUNTRY_FM = 'FM';
	const COUNTRY_MD = 'MD';
	const COUNTRY_MC = 'MC';
	const COUNTRY_MN = 'MN';
	const COUNTRY_ME = 'ME';
	const COUNTRY_MS = 'MS';
	const COUNTRY_MA = 'MA';
	const COUNTRY_MZ = 'MZ';
	const COUNTRY_MM = 'MM';
	const COUNTRY_NA = 'NA';
	const COUNTRY_NR = 'NR';
	const COUNTRY_NP = 'NP';
	const COUNTRY_NL = 'NL';
	const COUNTRY_NC = 'NC';
	const COUNTRY_NZ = 'NZ';
	const COUNTRY_NI = 'NI';
	const COUNTRY_NE = 'NE';
	const COUNTRY_NG = 'NG';
	const COUNTRY_NU = 'NU';
	const COUNTRY_NF = 'NF';
	const COUNTRY_MP = 'MP';
	const COUNTRY_NO = 'NO';
	const COUNTRY_OM = 'OM';
	const COUNTRY_PK = 'PK';
	const COUNTRY_PW = 'PW';
	const COUNTRY_PS = 'PS';
	const COUNTRY_PA = 'PA';
	const COUNTRY_PG = 'PG';
	const COUNTRY_PY = 'PY';
	const COUNTRY_PE = 'PE';
	const COUNTRY_PH = 'PH';
	const COUNTRY_PN = 'PN';
	const COUNTRY_PL = 'PL';
	const COUNTRY_PT = 'PT';
	const COUNTRY_PR = 'PR';
	const COUNTRY_QA = 'QA';
	const COUNTRY_RE = 'RE';
	const COUNTRY_RO = 'RO';
	const COUNTRY_RU = 'RU';
	const COUNTRY_RW = 'RW';
	const COUNTRY_BL = 'BL';
	const COUNTRY_SH = 'SH';
	const COUNTRY_KN = 'KN';
	const COUNTRY_LC = 'LC';
	const COUNTRY_MF = 'MF';
	const COUNTRY_PM = 'PM';
	const COUNTRY_VC = 'VC';
	const COUNTRY_WS = 'WS';
	const COUNTRY_SM = 'SM';
	const COUNTRY_ST = 'ST';
	const COUNTRY_SA = 'SA';
	const COUNTRY_SN = 'SN';
	const COUNTRY_RS = 'RS';
	const COUNTRY_SC = 'SC';
	const COUNTRY_SL = 'SL';
	const COUNTRY_SG = 'SG';
	const COUNTRY_SX = 'SX';
	const COUNTRY_SK = 'SK';
	const COUNTRY_SI = 'SI';
	const COUNTRY_SB = 'SB';
	const COUNTRY_SO = 'SO';
	const COUNTRY_ZA = 'ZA';
	const COUNTRY_GS = 'GS';
	const COUNTRY_SS = 'SS';
	const COUNTRY_ES = 'ES';
	const COUNTRY_LK = 'LK';
	const COUNTRY_SD = 'SD';
	const COUNTRY_SR = 'SR';
	const COUNTRY_SJ = 'SJ';
	const COUNTRY_SZ = 'SZ';
	const COUNTRY_SE = 'SE';
	const COUNTRY_CH = 'CH';
	const COUNTRY_SY = 'SY';
	const COUNTRY_TW = 'TW';
	const COUNTRY_TJ = 'TJ';
	const COUNTRY_TZ = 'TZ';
	const COUNTRY_TH = 'TH';
	const COUNTRY_TL = 'TL';
	const COUNTRY_TG = 'TG';
	const COUNTRY_TK = 'TK';
	const COUNTRY_TO = 'TO';
	const COUNTRY_TT = 'TT';
	const COUNTRY_TN = 'TN';
	const COUNTRY_TR = 'TR';
	const COUNTRY_TM = 'TM';
	const COUNTRY_TC = 'TC';
	const COUNTRY_TV = 'TV';
	const COUNTRY_UG = 'UG';
	const COUNTRY_UA = 'UA';
	const COUNTRY_AE = 'AE';
	const COUNTRY_GB = 'GB';
	const COUNTRY_UM = 'UM';
	const COUNTRY_US = 'US';
	const COUNTRY_UY = 'UY';
	const COUNTRY_UZ = 'UZ';
	const COUNTRY_VU = 'VU';
	const COUNTRY_VE = 'VE';
	const COUNTRY_VN = 'VN';
	const COUNTRY_VG = 'VG';
	const COUNTRY_VI = 'VI';
	const COUNTRY_WF = 'WF';
	const COUNTRY_EH = 'EH';
	const COUNTRY_YE = 'YE';
	const COUNTRY_ZM = 'ZM';
	const COUNTRY_ZW = 'ZW';
	const COUNTRY_XG = 'XG';
	const COUNTRY_XH = 'XH';
	const COUNTRY_XI = 'XI';
	const COUNTRY_XJ = 'XJ';
	const COUNTRY_FX = 'FX';
	const COUNTRY_IC = 'IC';
	const COUNTRY_KV = 'KV';
	const COUNTRY_XZ = 'XZ';
	const COUNTRY_XA = 'XA';
	const COUNTRY_DG = 'DG';
	const COUNTRY_HI = 'HI';
	
	static $map = array(
		self::COUNTRY_A => 'ALL',//代表所有国家
		self::COUNTRY_AF => '阿富汗',
		self::COUNTRY_AX => '奥兰群岛',
		self::COUNTRY_AL => '阿尔巴尼亚',
		self::COUNTRY_DZ => '阿尔及利亚',
		self::COUNTRY_AS => '美属萨摩亚',
		self::COUNTRY_AD => '安道尔',
		self::COUNTRY_AO => '安哥拉',
		self::COUNTRY_AI => '安圭拉',
		self::COUNTRY_AQ => '南极洲',
		self::COUNTRY_AG => '安提瓜和巴布达',
		self::COUNTRY_AR => '阿根廷',
		self::COUNTRY_AM => '亚美尼亚',
		self::COUNTRY_AW => '阿鲁巴',
		self::COUNTRY_AU => '澳大利亚',
		self::COUNTRY_AT => '奥地利',
		self::COUNTRY_AZ => '阿塞拜疆',
		self::COUNTRY_BS => '巴哈马',
		self::COUNTRY_BH => '巴林',
		self::COUNTRY_BD => '孟加拉国',
		self::COUNTRY_BB => '巴巴多斯',
		self::COUNTRY_BY => '白俄罗斯',
		self::COUNTRY_BE => '比利时',
		self::COUNTRY_BZ => '伯利兹',
		self::COUNTRY_BJ => '贝宁',
		self::COUNTRY_BM => '百慕大',
		self::COUNTRY_BT => '不丹',
		self::COUNTRY_BO => '玻利维亚',
		self::COUNTRY_BQ => '博内尔岛、圣尤斯特歇斯岛、萨巴',
		self::COUNTRY_BA => '波斯尼亚和黑塞哥维那',
		self::COUNTRY_BW => '博茨瓦纳',
		self::COUNTRY_BV => '布维岛',
		self::COUNTRY_BR => '巴西',
		self::COUNTRY_IO => '英属印度洋领土',
		self::COUNTRY_BN => '文莱',
		self::COUNTRY_BG => '保加利亚',
		self::COUNTRY_BF => '布基纳法索',
		self::COUNTRY_BI => '布隆迪',
		self::COUNTRY_CV => '佛得角',
		self::COUNTRY_KH => '柬埔寨',
		self::COUNTRY_CM => '喀麦隆',
		self::COUNTRY_CA => '加拿大',
		self::COUNTRY_KY => '开曼群岛',
		self::COUNTRY_CF => '中非',
		self::COUNTRY_TD => '乍得',
		self::COUNTRY_CL => '智利',
		self::COUNTRY_CN => '中国',
		self::COUNTRY_CX => '圣诞岛',
		self::COUNTRY_CC => '科科斯(基林)群岛',
		self::COUNTRY_Co => '哥伦比亚',
		self::COUNTRY_KM => '科摩罗',
		self::COUNTRY_CG => '刚果(布)',
		self::COUNTRY_CD => '刚果(金)',
		self::COUNTRY_CK => '库克群岛',
		self::COUNTRY_CR => '哥斯达黎加',
		self::COUNTRY_CI => '科特迪瓦',
		self::COUNTRY_HR => '克罗地亚',
		self::COUNTRY_CU => '古巴',
		self::COUNTRY_CW => '库拉索',
		self::COUNTRY_CY => '塞浦路斯',
		self::COUNTRY_CZ => '捷克',
		self::COUNTRY_DK => '丹麦',
		self::COUNTRY_DJ => '吉布提',
		self::COUNTRY_DM => '多米尼克',
		self::COUNTRY_DO => '多米尼加共和国',
		self::COUNTRY_EC => '厄瓜多尔',
		self::COUNTRY_EG => '埃及',
		self::COUNTRY_SV => '萨尔瓦多',
		self::COUNTRY_GQ => '赤道几内亚',
		self::COUNTRY_ER => '厄立特里亚',
		self::COUNTRY_EE => '爱沙尼亚',
		self::COUNTRY_ET => '埃塞俄比亚',
		self::COUNTRY_Fk => '马尔维纳斯群岛(福克兰群岛)',
		self::COUNTRY_FO => '法罗群岛',
		self::COUNTRY_FJ => '斐济',
		self::COUNTRY_FI => '芬兰',
		self::COUNTRY_FR => '法国',
		self::COUNTRY_GF => '法属圭亚那',
		self::COUNTRY_PF => '法属波利尼西亚',
		self::COUNTRY_TF => '法属南部领土',
		self::COUNTRY_GA => '加蓬',
		self::COUNTRY_GM => '冈比亚',
		self::COUNTRY_GE => '格鲁吉亚',
		self::COUNTRY_DE => '德国',
		self::COUNTRY_GH => '加纳',
		self::COUNTRY_GI => '直布罗陀',
		self::COUNTRY_GR => '希腊',
		self::COUNTRY_GL => '格陵兰',
		self::COUNTRY_GD => '格林纳达',
		self::COUNTRY_GP => '瓜德罗普',
		self::COUNTRY_GU => '关岛',
		self::COUNTRY_GT => '危地马拉',
		self::COUNTRY_GG => '根西岛',
		self::COUNTRY_GN => '几内亚',
		self::COUNTRY_GW => '几内亚比绍',
		self::COUNTRY_GY => '圭亚那',
		self::COUNTRY_HT => '海地',
		self::COUNTRY_HM => '赫德岛和麦克唐纳岛',
		self::COUNTRY_VA => '梵蒂冈',
		self::COUNTRY_HN => '洪都拉斯',
		self::COUNTRY_HK => '中国香港',
		self::COUNTRY_HU => '匈牙利',
		self::COUNTRY_IS => '冰岛',
		self::COUNTRY_IN => '印度',
		self::COUNTRY_ID => '印度尼西亚',
		self::COUNTRY_IR => '伊朗',
		self::COUNTRY_IQ => '伊拉克',
		self::COUNTRY_IE => '爱尔兰',
		self::COUNTRY_IM => '马恩岛',
		self::COUNTRY_IL => '以色列',
		self::COUNTRY_IT => '意大利',
		self::COUNTRY_JM => '牙买加',
		self::COUNTRY_JP => '日本',
		self::COUNTRY_JE => '泽西岛',
		self::COUNTRY_JO => '约旦',
		self::COUNTRY_KZ => '哈萨克斯坦',
		self::COUNTRY_KE => '肯尼亚',
		self::COUNTRY_KI => '基里巴斯',
		self::COUNTRY_KP => '朝鲜',
		self::COUNTRY_KR => '韩国',
		self::COUNTRY_KW => '科威特',
		self::COUNTRY_KG => '吉尔吉斯斯坦',
		self::COUNTRY_LA => '老挝',
		self::COUNTRY_LV => '拉脱维亚',
		self::COUNTRY_LB => '黎巴嫩',
		self::COUNTRY_LS => '莱索托',
		self::COUNTRY_LR => '利比里亚',
		self::COUNTRY_LY => '利比亚',
		self::COUNTRY_LI => '列支敦士登',
		self::COUNTRY_LT => '立陶宛',
		self::COUNTRY_LU => '卢森堡',
		self::COUNTRY_MO => '中国澳门',
		self::COUNTRY_MK => '马其顿',
		self::COUNTRY_MG => '马达加斯加',
		self::COUNTRY_MW => '马拉维',
		self::COUNTRY_MY => '马来西亚',
		self::COUNTRY_MV => '马尔代夫',
		self::COUNTRY_ML => '马里',
		self::COUNTRY_MT => '马耳他',
		self::COUNTRY_MH => '马绍尔群岛',
		self::COUNTRY_MQ => '马提尼克',
		self::COUNTRY_MR => '毛里塔尼亚',
		self::COUNTRY_MU => '毛里求斯',
		self::COUNTRY_YT => '马约特',
		self::COUNTRY_MX => '墨西哥',
		self::COUNTRY_FM => '密克罗尼西亚',
		self::COUNTRY_MD => '摩尔多瓦',
		self::COUNTRY_MC => '摩纳哥',
		self::COUNTRY_MN => '蒙古',
		self::COUNTRY_ME => '黑山共和国',
		self::COUNTRY_MS => '蒙特塞拉特',
		self::COUNTRY_MA => '摩洛哥',
		self::COUNTRY_MZ => '莫桑比克',
		self::COUNTRY_MM => '缅甸',
		self::COUNTRY_NA => '纳米比亚',
		self::COUNTRY_NR => '瑙鲁',
		self::COUNTRY_NP => '尼泊尔',
		self::COUNTRY_NL => '荷兰',
		self::COUNTRY_NC => '新喀里多尼亚',
		self::COUNTRY_NZ => '新西兰',
		self::COUNTRY_NI => '尼加拉瓜',
		self::COUNTRY_NE => '尼日尔',
		self::COUNTRY_NG => '尼日利亚',
		self::COUNTRY_NU => '纽埃',
		self::COUNTRY_NF => '诺福克岛',
		self::COUNTRY_MP => '北马里亚纳',
		self::COUNTRY_NO => '挪威',
		self::COUNTRY_OM => '阿曼',
		self::COUNTRY_PK => '巴基斯坦',
		self::COUNTRY_PW => '帕劳',
		self::COUNTRY_PS => '巴勒斯坦',
		self::COUNTRY_PA => '巴拿马',
		self::COUNTRY_PG => '巴布亚新几内亚',
		self::COUNTRY_PY => '巴拉圭',
		self::COUNTRY_PE => '秘鲁',
		self::COUNTRY_PH => '菲律宾',
		self::COUNTRY_PN => '皮特凯恩群岛',
		self::COUNTRY_PL => '波兰',
		self::COUNTRY_PT => '葡萄牙',
		self::COUNTRY_PR => '波多黎各',
		self::COUNTRY_QA => '卡塔尔',
		self::COUNTRY_RE => '留尼汪',
		self::COUNTRY_RO => '罗马尼亚',
		self::COUNTRY_RU => '俄罗斯',
		self::COUNTRY_RW => '卢旺达',
		self::COUNTRY_BL => '圣巴泰勒米岛',
		self::COUNTRY_SH => '圣赫勒拿',
		self::COUNTRY_KN => '圣基茨和尼维斯',
		self::COUNTRY_LC => '圣卢西亚',
		self::COUNTRY_MF => '法属圣马丁',
		self::COUNTRY_PM => '圣皮埃尔和密克隆',
		self::COUNTRY_VC => '圣文森特和格林纳丁斯',
		self::COUNTRY_WS => '西萨摩亚',
		self::COUNTRY_SM => '圣马力诺',
		self::COUNTRY_ST => '圣多美和普林西比',
		self::COUNTRY_SA => '沙特阿拉伯',
		self::COUNTRY_SN => '塞内加尔',
		self::COUNTRY_RS => '塞尔维亚',
		self::COUNTRY_SC => '塞舌尔',
		self::COUNTRY_SL => '塞拉利昂',
		self::COUNTRY_SG => '新加坡',
		self::COUNTRY_SX => '荷属圣马丁',
		self::COUNTRY_SK => '斯洛伐克',
		self::COUNTRY_SI => '斯洛文尼亚',
		self::COUNTRY_SB => '所罗门群岛',
		self::COUNTRY_SO => '索马里',
		self::COUNTRY_ZA => '南非',
		self::COUNTRY_GS => '南乔治亚岛和南桑德韦奇岛',
		self::COUNTRY_SS => '南苏丹',
		self::COUNTRY_ES => '西班牙',
		self::COUNTRY_LK => '斯里兰卡',
		self::COUNTRY_SD => '苏丹',
		self::COUNTRY_SR => '苏里南',
		self::COUNTRY_SJ => '斯瓦尔巴群岛',
		self::COUNTRY_SZ => '斯威士兰',
		self::COUNTRY_SE => '瑞典',
		self::COUNTRY_CH => '瑞士',
		self::COUNTRY_SY => '叙利亚',
		self::COUNTRY_TW => '中国台湾',
		self::COUNTRY_TJ => '塔吉克斯坦',
		self::COUNTRY_TZ => '坦桑尼亚',
		self::COUNTRY_TH => '泰国',
		self::COUNTRY_TL => '东帝汶',
		self::COUNTRY_TG => '多哥',
		self::COUNTRY_TK => '托克劳',
		self::COUNTRY_TO => '汤加',
		self::COUNTRY_TT => '特立尼达和多巴哥',
		self::COUNTRY_TN => '突尼斯',
		self::COUNTRY_TR => '土耳其',
		self::COUNTRY_TM => '土库曼斯坦',
		self::COUNTRY_TC => '特克斯科斯群岛',
		self::COUNTRY_TV => '图瓦卢',
		self::COUNTRY_UG => '乌干达',
		self::COUNTRY_UA => '乌克兰',
		self::COUNTRY_AE => '阿闻酋',
		self::COUNTRY_GB => '英国',
		self::COUNTRY_UM => '美属太平洋各群岛',
		self::COUNTRY_US => '美国',
		self::COUNTRY_UY => '乌拉圭',
		self::COUNTRY_UZ => '乌兹别克斯坦',
		self::COUNTRY_VU => '瓦努阿图',
		self::COUNTRY_VE => '委内瑞拉',
		self::COUNTRY_VN => '越南',
		self::COUNTRY_VG => '英属维尔京群岛',
		self::COUNTRY_VI => '美属维尔京群岛',
		self::COUNTRY_WF => '瓦利斯和富图纳群岛',
		self::COUNTRY_EH => '西撒哈拉',
		self::COUNTRY_YE => '也门',
		self::COUNTRY_ZM => '赞比亚',
		self::COUNTRY_ZW => '津巴布韦',
		self::COUNTRY_XG => '北非西班牙属土',
		self::COUNTRY_XH => '亚速尔群岛',
		self::COUNTRY_XI => '马德拉岛',
		self::COUNTRY_XJ => '巴利阿里群岛',
		self::COUNTRY_FX => '法属美特罗波利坦',
		self::COUNTRY_IC => '加那利群岛',
		self::COUNTRY_KV => '科索沃',
		self::COUNTRY_XZ => '桑给巴尔',
		self::COUNTRY_XA => '奥尔德尼岛',
		self::COUNTRY_DG => '迪戈加西亚岛',
		self::COUNTRY_HI => '中途岛(美)',
	);
}