<?php

namespace express_4px\oms\fu_wms_outbound_create\v100;

class CreateOutboundErrorCode{
	const AVALIABLE_STOCK_IS_NOT_ENOUGH = 'AVALIABLE_STOCK_IS_NOT_ENOUGH';
	const ERR_OUTBOUND_CONSIGNMENT_REF_NO_EMPTY = 'ERR_OUTBOUND_CONSIGNMENT_REF_NO_EMPTY';
	const ERR_REF_NO_LENGTH_BEYOND = 'ERR_REF_NO_LENGTH_BEYOND';
	const ERR_OUTBOUND_CONSIGNMENT_FROM_WAREHOUSE_CODE_EMPTY = 'ERR_OUTBOUND_CONSIGNMENT_FROM_WAREHOUSE_CODE_EMPTY';
	const ERR_OUTBOUND_CONSIGNMENT_CONSIGNMENT_TYPE_EMPTY = 'ERR_OUTBOUND_CONSIGNMENT_CONSIGNMENT_TYPE_EMPTY';
	const ERR_OUTBOUND_CONSIGNMENT_LOGISTICS_PRODUCT_EMPTY = 'ERR_OUTBOUND_CONSIGNMENT_LOGISTICS_PRODUCT_EMPTY';
	const ERR_OUTBOUND_CONSIGNMENT_COUNTRY_EMPTY = 'ERR_OUTBOUND_CONSIGNMENT_COUNTRY_EMPTY';
	const ERR_OUTBOUND_CONSIGNMENT_STREET_EMPTY = 'ERR_OUTBOUND_CONSIGNMENT_STREET_EMPTY';
	const ERR_OUTBOUND_CONSIGNMENT_FIRST_NAME_EMPTY = 'ERR_OUTBOUND_CONSIGNMENT_FIRST_NAME_EMPTY';
	const ERR_OUTBOUND_CONSIGNMENT_EMAIL_ILLEGAL = 'ERR_OUTBOUND_CONSIGNMENT_EMAIL_ILLEGAL';
	const ERR_OUTBOUND_CONSIGNMENT_SKU_EMPTY = 'ERR_OUTBOUND_CONSIGNMENT_SKU_EMPTY';
	const ERR_OUTBOUND_CONSIGNMENT_SKU_QTY_FORMAT = 'ERR_OUTBOUND_CONSIGNMENT_SKU_QTY_FORMAT';
	
	static $codeMessageMap = array(
		self::AVALIABLE_STOCK_IS_NOT_ENOUGH                      => '库存不足',
		self::ERR_OUTBOUND_CONSIGNMENT_REF_NO_EMPTY              => '出库委托[参考号]不能为空',
		self::ERR_REF_NO_LENGTH_BEYOND                           => '客户参考号长度超出',
		self::ERR_OUTBOUND_CONSIGNMENT_FROM_WAREHOUSE_CODE_EMPTY => '出库委托[出库仓库]不能为空',
		self::ERR_OUTBOUND_CONSIGNMENT_CONSIGNMENT_TYPE_EMPTY    => '出库委托[委托类型]不能为空',
		self::ERR_OUTBOUND_CONSIGNMENT_LOGISTICS_PRODUCT_EMPTY   => '出库委托[派送方式]不能为空',
		self::ERR_OUTBOUND_CONSIGNMENT_COUNTRY_EMPTY             => '出库委托[国家]不能为空',
		self::ERR_OUTBOUND_CONSIGNMENT_STREET_EMPTY              => '出库委托[街道]不能为空',
		self::ERR_OUTBOUND_CONSIGNMENT_FIRST_NAME_EMPTY          => '出库委托[收件人名]不能为空',
		self::ERR_OUTBOUND_CONSIGNMENT_EMAIL_ILLEGAL             => '邮箱格式错误',
		self::ERR_OUTBOUND_CONSIGNMENT_SKU_EMPTY                 => '出库委托[SKU]不能为空',
		self::ERR_OUTBOUND_CONSIGNMENT_SKU_QTY_FORMAT            => '出库委托[SKU数量]只能为正整数',
	);
	
}