<?php

namespace express_4px\oms\fu_wms_inbound_cancel\v100;

class CancelInboundErrorCode{
	const ERR_INBOUND_CONSIGNMENT_CONSINGNMENTNO_AND_REFNO_EMPTY= 'ERR_INBOUND_CONSIGNMENT_CONSINGNMENTNO_AND_REFNO_EMPTY';
	const ERR_INBOUND_CONSIGNMENT_NOT_FOUND_CONSINGNMENTNO_EMPTY= 'ERR_INBOUND_CONSIGNMENT_NOT_FOUND_CONSINGNMENTNO_EMPTY';
	const ERR_INBOUND_CONSIGNMENT_NOT_FOUND_CONSINGNMENTNO_NULL= 'ERR_INBOUND_CONSIGNMENT_NOT_FOUND_CONSINGNMENTNO_NULL';
	const ERR_INBOUND_CONSIGNMENT_STATUS_CANNOT_CANCEL= 'ERR_INBOUND_CONSIGNMENT_STATUS_CANNOT_CANCEL';
	
	static $codeMessageMap = array(
		self::ERR_INBOUND_CONSIGNMENT_CONSINGNMENTNO_AND_REFNO_EMPTY => '入库委托单号和参考号不能全为空',
		self::ERR_INBOUND_CONSIGNMENT_NOT_FOUND_CONSINGNMENTNO_EMPTY => '入库委托单号不能为空',
		self::ERR_INBOUND_CONSIGNMENT_NOT_FOUND_CONSINGNMENTNO_NULL  => '入库委托单不存在',
		self::ERR_INBOUND_CONSIGNMENT_STATUS_CANNOT_CANCEL           => '入库委托单当前状态,不能进行取消操作',
	);
	
}